name: Workflow Secret

on: push


jobs:
  display_value:
    runs-on: ubuntu-latest

    steps: 
      - run: |
          echo "${{ secrets.DATABASE_PASSWORD }}"
          echo "${{ vars.VERSION }}"
      - name: GitHub Script
        id: step-return
        uses: actions/github-script@v7.0.1
        with:
          script: return "Mon retour";
          
