name: Workflow Secret

on: push


jobs:
  display_value:
    runs-on: ubuntu-latest
    outputs: 
      MON_RETOUT: ${{ steps.step-return.outputs.result }}
    steps: 
      - run: |
          echo "${{ secrets.DATABASE_PASSWORD }}"
          echo "${{ vars.VERSION }}"
      - name: GitHub Script
        id: step-return
        uses: actions/github-script@v7.0.1
        with:
          script: return "Mon retour";
  dispaly-return:
    runs-on: ubuntu-latest
    needs: [display_value]
    steps:
      - run: echo "${{ needs.display_value.outputs.MON_RETOUT }}"
          
